# -*- coding: utf-8 -*-
"""(202210930)-LeenHaroun-(202210895)SondosSukkarieh-Phase2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhBw1Abmy2xB6RwLlAmP7tuUGCyKkA1F

***Task 1: Plotly***
"""

import pandas as pd
import plotly.express as px

# Load dataset
df = pd.read_csv('retail_store_sales.csv')
df.columns = df.columns.str.strip()

# Clean data
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], dayfirst=True, errors='coerce')
for col in ['Price Per Unit', 'Quantity', 'Total Spent']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df = df.dropna(subset=['Transaction Date', 'Category', 'Total Spent', 'Quantity'])
df['Month'] = df['Transaction Date'].dt.to_period('M').dt.to_timestamp()
df['Month Label'] = df['Month'].dt.strftime('%Y-%m')
df.head()

category_summary = (
    df.groupby('Category', as_index=False)
      .agg(Total_Sales=('Total Spent', 'sum'),
           Transactions=('Transaction ID', 'count'),
           Average_Transaction=('Total Spent', 'mean'),
           Total_Quantity=('Quantity', 'sum'))
      .sort_values('Total_Sales', ascending=True)
)

fig1 = px.bar(
    category_summary,
    x='Total_Sales',
    y='Category',
    orientation='h',
    color='Category',
    title='Interactive Chart 1: Total Sales by Product Category',
    labels={'Total_Sales': 'Total Sales', 'Category': 'Product Category'},
    hover_data={
        'Total_Sales': ':,.2f',
        'Transactions': ':,',
        'Average_Transaction': ':,.2f',
        'Total_Quantity': ':,.0f',
        'Category': True
    }
)
fig1.update_layout(template='plotly_white', showlegend=False, title_x=0.5, dragmode='zoom')
fig1.show()

monthly_location = (
    df.groupby(['Month', 'Location'], as_index=False)
      .agg(Total_Sales=('Total Spent', 'sum'), Transactions=('Transaction ID', 'count'))
      .sort_values('Month')
)

fig2 = px.line(
    monthly_location,
    x='Month',
    y='Total_Sales',
    color='Location',
    markers=True,
    title='Interactive Chart 2: Monthly Sales Trend by Location (Multi-Trace)',
    labels={'Month': 'Month', 'Total_Sales': 'Total Sales', 'Location': 'Location'},
    hover_data={'Total_Sales': ':,.2f', 'Transactions': ':,'}
)
fig2.update_layout(
    template='plotly_white',
    title_x=0.5,
    hovermode='x unified',
    dragmode='zoom',
    xaxis=dict(rangeslider=dict(visible=True), type='date'),
    legend_title_text='Click to filter location'
)
fig2.show()

monthly_category = (
    df.groupby(['Month Label', 'Category'], as_index=False)
      .agg(Total_Sales=('Total Spent', 'sum'),
           Total_Quantity=('Quantity', 'sum'),
           Transactions=('Transaction ID', 'count'),
           Average_Transaction=('Total Spent', 'mean'))
      .sort_values(['Month Label', 'Total_Sales'], ascending=[True, False])
)

fig3 = px.bar(
    monthly_category,
    x='Category',
    y='Total_Sales',
    color='Category',
    animation_frame='Month Label',
    title='Interactive Chart 3: Animated Monthly Sales by Category',
    labels={'Category': 'Category', 'Total_Sales': 'Total Sales', 'Month Label': 'Month'},
    hover_data={
        'Total_Sales': ':,.2f',
        'Total_Quantity': ':,.0f',
        'Transactions': ':,',
        'Average_Transaction': ':,.2f'
    }
)
fig3.update_layout(template='plotly_white', title_x=0.5, dragmode='zoom', xaxis_tickangle=-35, legend_title_text='Click to filter category')
fig3.show()

fig1.write_html('chart1_total_sales_by_category.html')
fig2.write_html('chart2_monthly_sales_by_location.html')
fig3.write_html('chart3_animated_monthly_sales_by_category.html')
print('Interactive HTML charts exported successfully.')

!pip install dash plotly pandas -q

import pandas as pd
import plotly.express as px
from dash import Dash, dcc, html, Input, Output

df = pd.read_csv("/content/retail_store_sales.csv")

df["Transaction Date"] = pd.to_datetime(df["Transaction Date"], errors="coerce", dayfirst=True)
df["Year"] = df["Transaction Date"].dt.year

app = Dash(__name__)

app.layout = html.Div([
    html.H2("Retail Store Sales Dashboard"),

    html.Label("Select Category:"),
    dcc.Dropdown(
        id="category",
        options=[{"label": c, "value": c} for c in sorted(df["Category"].dropna().unique())],
        value=sorted(df["Category"].dropna().unique())[0],
        clearable=False
    ),

    html.Label("Select Year:"),
    dcc.Slider(
        id="year",
        min=int(df["Year"].min()),
        max=int(df["Year"].max()),
        value=int(df["Year"].min()),
        marks={int(y): str(int(y)) for y in sorted(df["Year"].dropna().unique())}
    ),

    dcc.Graph(id="chart1"),
    dcc.Graph(id="chart2")
])

@app.callback(
    [Output("chart1", "figure"),
     Output("chart2", "figure")],
    [Input("category", "value"),
     Input("year", "value")]
)
def update_dashboard(category, year):
    dff = df[(df["Category"] == category) & (df["Year"] == year)]

    fig1 = px.bar(
        dff,
        x="Item",
        y="Total Spent",
        color="Payment Method",
        title="Total Sales by Item",
        hover_data=["Quantity", "Price Per Unit", "Location"]
    )

    fig2 = px.scatter(
        dff,
        x="Price Per Unit",
        y="Total Spent",
        size="Quantity",
        color="Payment Method",
        title="Price Per Unit vs Total Spent",
        hover_data=["Item", "Quantity", "Location"]
    )

    return fig1, fig2

app.run(jupyter_mode="inline", debug=False)

!unzip "/content/Task2_Dash_Application_Files (1).zip"